version: '2'
services:
  db:
    image: postgres:10.1
    ports:
      - "5432:5432"
    env_file:
      - .env

  redis:
    image: redis:4
    ports:
      - "6479:6379"

  web:
    build: .
    command: bundle exec rails server -p 3000 -b 0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - db
      - sidekiq
    volumes:
      - .:/app
    env_file:
      - .env

  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - redis
    volumes:
      - .:/app
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - .:/app
